import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/store/provider";
import { Header } from "@/components/header/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RickAndMorty",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/icons8-rick-sanchez.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="mx-auto flex flex-col min-h-screen min-w-[320px]">
            <Header />
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
